### PR TITLE
remove MaterializeCSS and JQuery legacy bundles and update composer.json

### PR DESCRIPTION
**Pull request by symartin**
## Description

Le but est de lentement monter en version pour rattraper la dette technique qui c'est accumulée ces dernières années. Les bundle de Materialize et JQuery ne sont plus maintenus et était un goulot d'étranglement bloquant la mise à jour de bcp d'autres.

Comme cela implique bcp de changements ds les dépendances, il serait sens doute preferable de tester les minutieusement tt les fonctionnalités.

Les parties basées sur les api extérieures (Helloasso and co ...) n'ont pas pu être testé

## Liste des modifications
 - Removing zendframework/zend-eventmanager (3.2.1) -> remplacé par laminas/laminas-eventmanager (dépendance de doctrine/migrations)
 - Removing zendframework/zend-code (3.4.1)  -> remplacé par laminas/laminas-code (dépendance de doctrine/migrations)
 - Removing evheniy/materialize-bundle (1.2.0) -> plus maintenus 
 - Removing evheniy/jquery-bundle (1.5.1) -> plus maintenus 
 - Removing components/jquery (3.5.1) -> n'est pas utilisé 🤷‍♂️, je pense que c'est un package prévu pour Symfony flex que l'on utilise pas (encore...)
 - Upgrading composer/package-versions-deprecated (1.11.99.1 => 1.11.99.5)
 - Installing doctrine/deprecations (v1.0.0)
 - Upgrading symfony/polyfill-php72 (v1.20.0 => v1.26.0)
 - Upgrading symfony/polyfill-mbstring (v1.20.0 => v1.26.0)
 - Upgrading symfony/polyfill-ctype (v1.20.0 => v1.26.0)
 - Upgrading twig/twig (v2.14.1 => v2.15.3)
 - Upgrading symfony/polyfill-intl-icu (v1.20.0 => v1.26.0)
 - Upgrading symfony/polyfill-apcu (v1.20.0 => v1.26.0)
 - Upgrading psr/log (1.1.3 => 1.1.4)
 - Upgrading psr/container (1.0.0 => 1.1.2)
 - Upgrading fig/link-util (1.1.1 => 1.1.2)
 - Upgrading doctrine/lexer (1.2.1 => 1.2.3)
 - Upgrading doctrine/annotations (1.11.1 => 1.13.3)
 - Upgrading doctrine/reflection (1.2.2 => 1.2.3)
 - Upgrading doctrine/event-manager (1.1.1 => 1.1.2 => v1.2.0)
 - Upgrading doctrine/collections (1.6.7 => 1.8.0)
 - Upgrading doctrine/cache (1.10.2 => 1.13.0)
 - Upgrading doctrine/inflector (1.4.3 => 1.4.4)
 - Upgrading symfony/symfony (v3.4.46 => v3.4.49)
 - Installing webimpress/safe-writer (2.2.0)
 - Installing laminas/laminas-zendframework-bridge (1.6.1)
 - Installing laminas/laminas-eventmanager (3.5.0)
 - Installing laminas/laminas-code (3.5.1)
 - Upgrading ocramius/proxy-manager (2.2.3 => 2.7.2)
 - Upgrading doctrine/dbal (2.12.1 => 2.13.9)
 - Upgrading doctrine/migrations (2.3.0 => 2.3.1)
 - Installing symfony/deprecation-contracts (v2.5.2)
 - Upgrading symfony/service-contracts (v2.2.0 => v2.5.2)
 - Upgrading doctrine/doctrine-bundle (1.12.12 => 1.12.13)
 - Upgrading doctrine/doctrine-migrations-bundle (2.2.1 => 2.2.3)
 - Upgrading doctrine/instantiator (1.4.0 => 1.4.1)
 - Upgrading doctrine/orm (2.7.4 => 2.7.5)
 - Upgrading symfony/polyfill-intl-normalizer (v1.20.0 => v1.26.0)
 - Upgrading symfony/polyfill-intl-idn (v1.20.0 => v1.26.0)
 - Upgrading egulias/email-validator (2.1.24 => 3.2.1)
 - Upgrading paragonie/random_compat (v2.0.19 => v2.0.21)
 - Upgrading friendsofsymfony/oauth2-php (1.3.0 => 1.3.1)
 - Upgrading incenteev/composer-parameter-handler (v2.1.4 => v2.1.5)
 - Upgrading michelf/php-markdown (1.9.0 => 1.9.1)
 - Upgrading symfony/polyfill-php80 (v1.20.0 => v1.26.0)
 - Upgrading nesbot/carbon (2.41.5 => 2.62.1)
 - Upgrading webmozart/assert (1.9.1 => 1.11.0)
 - Upgrading phpdocumentor/type-resolver (1.4.0 => 1.6.1=>1.6.2)
 - Upgrading phpdocumentor/reflection-docblock (5.2.2 => 5.3.0)
 - Upgrading phpunit/php-token-stream (3.1.1 => 3.1.3)
 - Upgrading sebastian/resource-operations (2.0.1 => 2.0.2)
 - Upgrading sebastian/recursion-context (3.0.0 => 3.0.1)
 - Upgrading sebastian/object-reflector (1.1.1 => 1.1.2)
 - Upgrading sebastian/object-enumerator (3.0.3 => 3.0.4)
 - Upgrading sebastian/exporter (3.1.2 => 3.1.5)
 - Upgrading sebastian/environment (4.2.3 => 4.2.4)
 - Upgrading sebastian/diff (3.0.2 => 3.0.3)
 - Upgrading sebastian/comparator (3.0.2 => 3.0.5)
 - Upgrading phpunit/php-timer (2.1.2 => 2.1.3)
 - Upgrading phpunit/php-file-iterator (2.0.2 => 2.0.5)
 - Upgrading theseer/tokenizer (1.2.0 => 1.2.1)
 - Upgrading sebastian/code-unit-reverse-lookup (1.0.1 => 1.0.2)
 - Upgrading phpspec/prophecy (1.12.1 => v1.15.0)
 - Upgrading myclabs/deep-copy (1.10.2 => 1.11.0)
 - Upgrading symfony/mime (v5.1.8 => v5.4.13)
 - Upgrading symfony/polyfill-php73 (v1.20.0 => v1.26.0)
 - Upgrading symfony/http-client-contracts (v2.3.1 => v2.5.2)
 - Upgrading symfony/http-client (v5.1.8 => v5.4.13 => v5.4.14)
 - Upgrading sensio/framework-extra-bundle (v3.0.29 => v5.4.1)
 - Upgrading tecnickcom/tcpdf (6.3.5 => 6.5.0)
 - Upgrading spipu/html2pdf (v5.2.2 => v5.2.5)
 - Upgrading monolog/monolog (1.25.5 => 1.27.1)
 - Upgrading symfony/phpunit-bridge (v4.4.16 => v4.4.44 => v4.4.47)
 - Installing symfony/polyfill-iconv (v1.26.0)
 - Upgrading swiftmailer/swiftmailer (v5.4.12 => v6.3.0)
 - Upgrading symfony/swiftmailer-bundle (v2.6.7 => v3.3.1)
 - Upgrading jms/metadata (2.3.0 => 2.7.0)
 - Upgrading behat/transliterator (v1.3.0 => v1.5.0)

_edit: update list with according to last composer.lock_

### CODE REVIEW

**Comment by raphodn** [comment]
Top !!!
j'ai commencé à tester, pour l'instant pas de soucis

**Comment by raphodn** [comment]
@symartin j'ai continué à tester, rien à signaler, sauf la génération de widget : http://membres.yourcoop.local:8000/admin/widget

**Comment by symartin** [comment]
@raphodn J'ai réparé la page /admin/widget, dis moi si tu trouve un autre problème :)

**Comment by symartin** [comment]
fix https://github.com/elefan-grenoble/gestion-compte/issues/464

**Pull request merged**
